### ISSUE TITLE
Compile failed!

### ISSUE THREAD

**Issue by dangdkhanh** [Lecrapouille/zipper#12]
I can't use this repo on vs2022,
it can compile but the generated library can't link, it seems like it's not ready yet!

![image](https://github.com/Lecrapouille/zipper/assets/99936463/8800c28d-e8df-43f0-9f6d-59e568acb01b)

**Comment by Lecrapouille** [comment]
Hi, you did not give lot of information. Anyway, do you compile correct files and defines ? See https://github.com/Lecrapouille/zipper/blob/16ebfebb25b1fc79f405d53326570fca2365d910/Makefile#L40

**Comment by dangdkhanh** [comment]
Hi,
Thank you. clearly I was missing them.

**Comment by Lecrapouille** [comment]
If it's working for you, would be nice to create a pull request since i'm not a windows user it's hard for me to give build system for other users.

**Comment by Lecrapouille** [comment]
@dangdkhanh I'm still interesting by your vs2022 build files, if you agree to share them :)
